// <auto-generated />
using System;
using Biblioteca.BD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.BD.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240805234701_PrimerTabla")]
    partial class PrimerTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.BD.Data.Entity.Editorial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("EditorialDomicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditorialMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditorialNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EditorialTelefono")
                        .HasColumnType("int");

                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Editoriales");
                });
#pragma warning restore 612, 618
        }
    }
}
